name: 04 - using actions

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        #step-0 checkout the code from the repository
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies

              run : npm ci
              working-directory: my-react-app

        #1.instal deps of our react application

        #execute automated test
