name: 10 -Controlling the execution Flow

on: 
    workflow_dispatch:
            inputs:
               debug:
                description: "Enable debug mode"
                type: boolean
                default: false     
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and Build
              run: echo "Linting and building"