name: 14 - working with artifacts

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
               working-directory: .github/14-artifacts
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3 
              with:
                   node-version: '20.x'
            - name: Download  dependencies
              uses: actions/cache@v3
              id: cache
              with:
                path: .github/14-artifacts/react-app/node_modules
                key: deps-node-modules-${{hashFiles('.github/14-artifacts/react-app/package-lock.json')}}
            - name: Install dependencies
              run: npm ci


    diploy:
         runs-on: ubuntu-latest
         steps:
            - name: Deploying to non prod
              run: echo " Deploying to NonProd"