name: 17 - Custom Actions - Composite 
run-name: 17 - Custom Actions - Composite | env - ${{inputs.target-env}}

on: 
    workflow_dispatch:
        inputs:
            target-env:
                description: which environment to target for dependency installation
                type: choice
                options:
                      - dev
                      - staging
                      - PROD

env:
    working-directory: .github/13-caching/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ${{env.working-directory}}
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node and NPM Dependecies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 20.x
                working-directory: ${{env.working-directory}}
                target-env: ${{inputs.target-env}}
            - name: Test
              run: npm run test
              working-directory: ${{env.working-directory}}
            - name: Build
              run: npm run build
              working-directory: ${{env.working-directory}}